# Generated by Django 2.0.2 on 2018-03-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rejestracja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imię', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('dietetyk', models.CharField(choices=[('1', 'Jan Kowalski'), ('2', 'Ada Wspaniała')], default='1', max_length=255)),
                ('dzień', models.CharField(choices=[('1', 'Poniedziałek'), ('2', 'Wtorek'), ('3', 'Środa'), ('4', 'Czwartek'), ('5', 'Piątek'), ('6', 'Sobota'), ('7', 'Niedziela')], max_length=255)),
                ('godzina', models.CharField(max_length=255)),
            ],
        ),
    ]
